{{- if or .Values.env .Values.branding.logo }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}-environment
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ .Release.Name }}-environment
  namespace: {{ .Release.Namespace }}
data:
  {{- if and .Values.branding.logo (not (hasKey (default dict .Values.env) "APP_LOGO_URL")) }}
  APP_LOGO_URL: {{ printf "/branding/%s" .Values.branding.fileName | quote }}
  {{- end }}
  {{- with .Values.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
